# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlBpx1bbCIZrJEAVLwvATpcXdj9FDw5c
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

import pandas as pd
diabetes_dataset = pd.read_csv('/content/diabetes (1).csv')

pd.read_csv?

diabetes_dataset.head()

diabetes_dataset.shape

diabetes_dataset.describe()

diabetes_dataset['Outcome'].value_counts()

diabetes_dataset.groupby('Outcome').mean()

# separating the data and labels
X = diabetes_dataset.drop(columns = 'Outcome', axis=1)
Y = diabetes_dataset['Outcome']

print(X)

print(Y)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(X)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
standardized_data = scaler.transform(X)

print(standardized_data)

X = standardized_data
Y = diabetes_dataset['Outcome']

print(X)
print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

from sklearn import svm
classifier = svm.SVC(kernel='linear')

#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

from sklearn.metrics import accuracy_score
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('Accuracy score of the training data : ', training_data_accuracy)

# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy score of the test data : ', test_data_accuracy)

import numpy as np
from sklearn.preprocessing import StandardScaler

input_data = (5,166,72,19,175,25.8,0.587,51)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# Re-instantiate and fit the scaler for robust prediction
# This assumes diabetes_dataset is available globally and consistent with initial feature extraction
# If diabetes_dataset is not available, you would need to re-load it or pass the original X
# For this context, we will re-create X from diabetes_dataset to fit the scaler
# You might need to ensure 'diabetes_dataset' is available in the global scope if this cell is run independently.

# First, get the original X (features) from the dataset to fit the scaler
# This re-creates X based on the assumption that 'diabetes_dataset' is still loaded.
import pandas as pd
original_X_for_scaler_fit = diabetes_dataset.drop(columns = 'Outcome', axis=1)

scaler = StandardScaler()
# Fit the scaler using the NumPy values of the DataFrame to avoid the UserWarning
scaler.fit(original_X_for_scaler_fit.values)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')







